name: 'github-secrets'
description: 'Action to add a github secret to repository/environment'
inputs:
  secret-level:  # id of input
    description: 'Secret Level ( Repository or Environment secret)'
    required: true
    default: 'Repository'
  secret-name:  # id of input
    description: 'Name of the secret to be updated'
    required: true
  secret-value:  # id of input
    description: 'Value of the secret to be updated'
    required: true
  org-name:  # id of input
    description: 'Name of the organization in which secrets needs to be added'
    required: true  
  repo-name:  # id of input
    description: 'Name of the repository in which secrets needs to be added'
    required: true    
  token:  # id of input
    description: 'Github Token'
    required: true   
outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node16'
  main: 'dist/index.js'
