name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        secret-name: NETLIFY_SITE_ID
        secret-value: this-is-a-test-id
        secret-level: Repository
        org-name: amitakesai
        repo-name: gh-actions-wf
        token: ${{ secrets.MY_PAT }}
    - uses: ./
      with:
        secret-name: NETLIFY_SITE_ID
        secret-value: this-is-a-test-id
        secret-level: environment
        env-name: Staging
        org-name: united-talent-agency
        repo-name: test-uta-automate
        token: ${{ secrets.MY_PAT }}

